---
title: "Landscape metrics"
output: bookdown::html_document2
---

```{r}
library(landscapemetrics)
library(tidyverse)
library(ggrepel)
library(readxl)
library(stars)
```

Восстанавливаем цветовую шкалу
```{r}
typesdf = read_excel('data/types.xlsx')
types = typesdf$type

colormap = read_table2('data/colormap.clr', 
                       col_names = c('N', 'R', 'G', 'B', 'A', 'type')) %>% 
  filter(type %in% types)

pal = rgb(colormap$R/255, colormap$G/255, colormap$B/255, colormap$A/255)

```

Грузим данные
```{r}
read_lc = function(file) {
  read_stars(file) %>% 
    select(type = 1) %>%
    mutate(typefac = factor(type, levels = types),
           urban = (type == 50),
           crops = (type == 40)) %>% 
    st_warp(crs = 32662)
}

salekhard = read_lc('data/SALEKHARD.tif')
moscow = read_lc('data/MOSCOW.tif')
rostov = read_lc('data/ROSTOV.tif')
ufa = read_lc('data/UFA.tif')
petro = read_lc('data/PETRO.tif')
surgut = read_lc('data/SURGUT.tif')
ustug = read_lc('data/USTUG.tif')
grozny = read_lc('data/GROZNY.tif')
voronezh = read_lc('data/VORONEZH.tif')
```

Визуализируем:
```{r, fig.width=6, fig.height=6}
plot_lc = function(lc) {
  ggplot() +
    geom_stars(data = lc['typefac']) +
    scale_fill_manual(values = pal, breaks = types, labels = typesdf$class, drop = FALSE) +
    coord_sf(crs = st_crs(lc)) +
    xlab('LON') + ylab('LAT') +
    theme_bw() + theme(legend.position = 'bottom', legend.title=element_blank()) +
    guides(fill = guide_legend(ncol=4))
}

plot_lc(salekhard)
plot_lc(moscow)
plot_lc(rostov)
plot_lc(ufa)
plot_lc(petro)
plot_lc(surgut)
plot_lc(ustug)
plot_lc(grozny)
plot_lc(voronezh)
```

Считаем метрики сложности:
```{r}
lands = lst(САЛЕХАРД = salekhard, МОСКВА = moscow, `РОСТОВ-НА-ДОНУ` = rostov, УФА = ufa, ПЕТРОЗАВОДСК = petro,
            ШАРЬЯ = ustug, ГРОЗНЫЙ = grozny, ВОРОНЕЖ = voronezh, СУРГУТ = surgut)

(metrics = imap(lands, function(land, name) {
  tibble(name = name,
         ent = lsm_l_ent(land) %>% pull(value),
         condent = lsm_l_condent(land) %>% pull(value),
         joinent = lsm_l_joinent(land) %>% pull(value),
         mutinf = lsm_l_mutinf(land) %>% pull(value),
         relmutinf = mutinf / ent,
         urban = 100 * sum(land$urban, na.rm = TRUE) / length(land$urban),
         crops = 100 * sum(land$crops, na.rm = TRUE) / length(land$crops))
}) %>% bind_rows())
```

```{r}
ggplot(metrics, mapping = aes(ent, relmutinf, label = name)) +
  geom_point()
```

# Пространственные данные

Читаем данные:
```{r}
scales = c(200, 500, 1000)
regions = c('МОСКВА', 'ПЕТРОЗАВОДСК', 'САЛЕХАРД', 'УФА', 'РОСТОВ-ДОН')

lindata = lapply(scales, function(scale) { 
    read_delim(paste0('tables/resLines', scale, '.txt'), delim = ';', locale = locale(decimal_mark = ".")) %>% 
    select(-ncol(.)) %>% 
    mutate(Scale = scale,
           Region = stringr::str_sub(Region, 1, nchar(Region) - nchar(as.character(Scale))))
  }) %>% 
  bind_rows() %>% 
  filter(!stringr::str_detect(Name, 'clip')) %>% 
  mutate(Layer = stringr::str_sub(Name, 1, 3),
         Dim = stringr::str_sub(Name, 4, 6)) %>% 
  filter(!(Layer %in% c('rlh', 'rlf', 'veg'))) %>% 
  mutate_all(~replace(., is.nan(.), 0))

pntdata = lapply(scales, function(scale) { 
    read_delim(paste0('tables/resPoints', scale, '.txt'), delim = ';', locale = locale(decimal_mark = ".")) %>% 
    select(-ncol(.)) %>% 
    mutate(Scale = scale,
           Region = stringr::str_sub(Region, 1, nchar(Region) - nchar(as.character(Scale))))
  }) %>% 
  bind_rows() %>% 
  mutate(Layer = stringr::str_sub(Name, 1, 3),
         Dim = stringr::str_sub(Name, 4, 6)) %>% 
  filter(!(Layer %in% c('rlh', 'rlf', 'veg')))

poldata = lapply(scales, function(scale) { 
    read_delim(paste0('tables/resPolygons', scale, '.txt'), delim = ';', locale = locale(decimal_mark = ".")) %>% 
    select(-ncol(.)) %>% 
    mutate(Scale = scale,
           Region = stringr::str_sub(Region, 1, nchar(Region) - nchar(as.character(Scale))))
  }) %>% 
  bind_rows() %>% 
  mutate(Layer = stringr::str_sub(Name, 1, 3),
         Dim = stringr::str_sub(Name, 4, 6)) %>% 
  filter(!(Layer %in% c('rlh', 'rlf', 'veg')))

nuniq = length(unique(poldata$Region))

inters = read_delim('tables/topLines.txt', delim = ';', locale = locale(decimal_mark = ".")) %>% 
  select(-ncol(.)) %>% 
  mutate(Scale = as.character(rep(scales, each = n()/3)),
         Region = stringr::str_sub(Region, 1, nchar(Region) - nchar(Scale)))
```

Подсчитаем суммарное количество социально-экономических точек:
```{r}
linpts = lindata %>% 
  group_by(Region, Scale) %>% 
  summarise(linnpts = sum(PointsNumber))
polpts = poldata %>% 
  group_by(Region, Scale) %>% 
  summarise(polnpts = sum(PointsNumber),
            area = 1e-6 * sum(TotalArea * (Layer == 'adm')))
pntpts = pntdata %>% 
  group_by(Region, Scale) %>% 
  summarise(pntnpts = sum(NumberOfObj))


stats = bind_cols(linpts, polpts, pntpts) %>% 
  select(name = Region, Scale, pntnpts, linnpts, polnpts, area) %>% 
  mutate(total = pntnpts + linnpts + polnpts,
         density = total / area) %>% 
  ungroup() %>% 
  mutate(name = ifelse(name == 'РОСТОВ-ДОН', 'РОСТОВ-НА-ДОНУ',
                       ifelse(name == 'УСТЮГ', 'ШАРЬЯ', name)))
```

Соединяем
```{r}
compare = left_join(stats, metrics)
```

Корреляционный и регрессионный анализ

```{r}
tab = compare %>% 
  filter(Scale == 200) 

ggplot(tab, mapping = aes(urban, density, label = name)) +
  geom_point() +
  geom_smooth(method = 'lm') +
  geom_text_repel(
    segment.size  = 0.3,
    segment.color = "grey50",
    direction     = "y",
    hjust         = 0
  ) +
  scale_x_log10()

ggplot(tab, mapping = aes(crops, density, label = name)) +
  geom_point() +
  geom_smooth(method = 'lm') +
  geom_text_repel(
    segment.size  = 0.3,
    segment.color = "grey50",
    direction     = "y",
    hjust         = 0
  ) +
  scale_x_log10()

ggplot(tab, mapping = aes(crops + urban, density, label = name)) +
  geom_point() +
  geom_smooth(method = 'lm') +
  geom_text_repel(
    segment.size  = 0.3,
    segment.color = "grey50",
    direction     = "y",
    hjust         = 0
  ) +
  scale_x_log10()

cor.test(tab$density, log(tab$urban + 1))
cor.test(tab$density, log(tab$crops + 1))
cor.test(tab$density, log(tab$crops + 1) + log(tab$urban + 1))

lm(density ~ log(urban + 1), tab)
lm(density ~ log(crops + 1), tab)
lm(density ~ log(crops + urban + 1), tab)
```








